### ISSUE TITLE
Decrementing negative numbers doesn't work correctly

### ISSUE THREAD

**Issue by Asmor** [cgjosephlee/increment_decrement#1]
Starting with 0, if you repeatedly decrement you'll get...

    0
    -1
    -0
    --1
    --0
    ---1

Basically it appears it's not catching the negative sign, so it parses `-1` as `1`. Also, it should never create `-0`, and in a case where it encounters `-0` it should treat it as `0`.

**Comment by cgjosephlee** [comment]
Thank you for the report. This in now fix in 6b1ff7e3c19cbb67322ba58c041bd79d33e6211a. Please update to the latest commit.
